apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: summit-sim-common
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  destination:
    namespace: summit-sim
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/bhamm-lab.git
    targetRevision: main
    path: kubernetes/charts/common
    helm:
      valuesObject:
        name: summit-sim
        externalSecrets:
          enabled: true
          secrets:
            - secretKey: OPENROUTER_API_KEY
              remoteRef:
                key: /default/summit-sim
                property: OPENROUTER_API_KEY
        dragonfly:
          enabled: true
          snapshot:
            enabled: true
            cron: "* */3 * * *"
            pvc:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 4Gi
        ingressRoutes:
          - name: summit-sim
            ingressClass: traefik-external
            websocket: true
            routes:
              - match: Host(`summit-sim.bhamm-lab.com`)
                kind: Rule
                services:
                  - name: summit-sim
                    scheme: http
                    port: http
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
