apiVersion: v1
kind: Service
metadata:
  name: summit-sim
  namespace: summit-sim
  labels:
    app: summit-sim
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: summit-sim
